language: node_js
node_js:
    - "0.11"

env: DB=couchdb

services:
    - couchdb

before_script:
    - kanso install
    - curl -X PUT localhost:5984/miniplan_test
    - kanso push http://localhost:5984/miniplan_test

